sudo: false

language: java

jdk:
  - openjdk8

env:
  global:
    - EPERUSTEET_SERVICE_DIR=$PWD/eperusteet/eperusteet/eperusteet-service

script:
  - nvm install 10.16.3
  - git clone --depth=1 https://github.com/Opetushallitus/eperusteet
  - git submodule update --recursive --init

  - echo 'Generate API...' && echo -en 'travis_fold:start:script.1\\r'
  - cd eperusteet/eperusteet && mvn dependency:resolve --batch-mode && cd ../..
  - echo -en 'travis_fold:end:script.1\\r'

  - yarn install --silent

  - cd eperusteet-frontend-utils/vue
  - yarn install --silent
  - yarn gen:api:eperusteet
  - rm -rf node_modules
  - cd ../..
  - yarn install --silent
  - yarn test:unit
  - yarn build

# before_script:
#   - echo $JAVA_HOME
#   - java -version
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
#
# script:
#   - nvm install 10.16.3
#   - yarn lint
#   - yarn build
#   - yarn test:unit
#
# after_script:
#   - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
#   - ./cc-test-reporter upload-coverage
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.cache
